# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - helm upgrade --install argo ./argocd

  docker:
    desc: build and push docker file
    dir: docker
    cmds:
      - docker build . -t kbudde/argo-sops-plugin:latest 
      - docker push kbudde/argo-sops-plugin:latest 
