apiVersion: v1
kind: Secret
metadata:
    name: example
type: Opaque
data:
    password: ENC[AES256_GCM,data:8dsw1dabIleekphAFKR6,iv:NwhCdnx6fqaUJdoHGlRi4yv4Kop4FvfiAFT31KhFDVA=,tag:LQQYimD+dqhSAe2wXM/8OQ==,type:str]
    someValue: ENC[AES256_GCM,data:rexVdO2IdQVAnZ8qubDo,iv:18x24PpCbXOpncjwPuhZWobsPeIP5B8nAZfyEpfaPvY=,tag:ILWvyv9AWQI0EaaGLfhMlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10efzgcr0e55nvlxx5jlsr9gf2gx7cexnqqwtkx7efm04u6t5e5kq7yvdl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbmxRanFwRVNMc3F5dkxV
            Nk05WDUrNjRFYzlzakQreWY2cEZUVTBIV1c4CitqNkFxbmRnbGhTMjFZVU5oRHdt
            b0lwUEIzTFNyYVdsQ29kano4emRaTWsKLS0tIHV5d0xaN2RUeTZFamlvNVVtZks5
            eDdMSzVVREZUdTlkMzJvVElrRExtZkEKDyPuhXbz1e/f00jo2HS+l9z+NJv5+JMx
            p8azCHhpm72pJdx70zaK98GZVY6dsW4vPLxAttKG7SktjIOllvziEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-29T21:37:49Z"
    mac: ENC[AES256_GCM,data:ipIhZuZyXK7+E0I1EZFxOClZoa9nY0MpjrN6u8fQRIPF7LuV4kjwWtXhoj85mY9or4TSY+ih2NvSJQ7s++e5v/6OL/H0W6QClhPUX01JykSpZZYGLUpe4yFM7Wp03Cq63acpQoaZfwfxBHAbQRS/nRJq8cRz0S9Ctm5i3IH1C8k=,iv:+yo1hDowQHtOe3imZR8p//VEKAL1vqEW2qMkUk4u4DE=,tag:kw3rsCaJSgT9m68p+7fKNw==,type:str]
    pgp: []
    encrypted_regex: ^data.*
    version: 3.7.1
