apiVersion: v1
kind: Secret
metadata:
    name: example-suffix
data:
    password: ENC[AES256_GCM,data:h1Sm/Jwm6IuG+2YAW4QAbUuPaPU=,iv:H4L1gavMsdT7lJEYZ446y+SZy4z2f+VENjiD0cjhXdg=,tag:xIeU/36Fi+wgGS3hzYmxHQ==,type:str]
    someotherValue: ENC[AES256_GCM,data:hce9dcMs4AZx8r552FPPyUsIQYU=,iv:QDRuypa/sVbP18GTpn4s+dY0/IjtHM+v96TfeH+d92A=,tag:VBUtHq9Ma8ulNXnxSdnzaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10efzgcr0e55nvlxx5jlsr9gf2gx7cexnqqwtkx7efm04u6t5e5kq7yvdl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOUpOc2JhMU43MjNGVzlx
            bGJZQWlCejU2Z0Ewb3B5d1hJdVBwSHRKZldRCmNieDZvaUZzWTI2VTZFM2lxT0s0
            cjM3UzNTYk1idmJJazZ2Zm9JTVpMeGcKLS0tIHhWYm5Rd0k5TnFROFVNWktyYThI
            MXdGQmljWHNHM0YxN3cxQ0dlZUZGTFkKRhQRhN86Um8YB+kaJa9FNJs5GJGwP7ai
            F5nPx/K1BbyzbkiWhkxtzD+lDvyblstqaN2xSNy4Q05olRe3JK5W6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-29T22:27:19Z"
    mac: ENC[AES256_GCM,data:HAe3SKWxwRkoPqgQhu9uqCJQvvfOl/Lb/CYkPn9gHKMVP48Fhf4hLnaddKR+CZRMzZFZK1sQzUBhCEYOFxaf++LNVuxa6EZd77Ebq2bbbqyZfY6GjGznKtfrJVylQM7PwXFnGWFVoSdm35gHrfWOMdbC27E9tlNTl25R3Zh0p1Q=,iv:Gb+qKixC2dUAeKa7cxSc7fmpW9RWCj/osBs0VddotDc=,tag:TRzIMke2LBLpOQB48i+kgQ==,type:str]
    pgp: []
    encrypted_regex: ^data.*
    version: 3.7.1
